package HolaApp;


/**
* HolaApp/HolaOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hola.idl
* jueves 23 de octubre de 2014 12H28' CEST
*/

public interface HolaOperations 
{
  String decirHola ();
  void tirar ();
} // interface HolaOperations
