package HolaApp;


/**
* HolaApp/Hola.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hola.idl
* jueves 23 de octubre de 2014 12H28' CEST
*/

public interface Hola extends HolaOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Hola
